networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge

services:
  beckend:
    image: ${DOCKER_REGISTRY-}scrapper
    build:
      context: .
      dockerfile: scrapper/Dockerfile
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - Pg.db
    environment:
      - NEO4J_URI=bolt://neo4j.db:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-password}
    restart: unless-stopped

  Pg.db:
    image: postgres
    networks:
      backend-network:
        aliases:
          - Pg.db
    environment:
      - POSTGRES_USER=Job
      - POSTGRES_PASSWORD=HKGUbkiwu13!
      - POSTGRES_DB=JobsDB
    ports: 
    - 5432:5432
    restart: unless-stopped

  # angular-app:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   networks:
  #     - frontend-network
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - beckend
  #   restart: unless-stopped
  
  
    